;============================================================================
; VARIABLES
;============================================================================

[variables]
colorBase=0,0,0,125
colorBG=100,100,100,50
colorFG=255,255,255,255
colorNone=0,0,0,0
disk1=C:
disk2=D:
fontName=pixelmix
fontSize=6

;============================================================================
; STYLES
;============================================================================

[styleText]
StringEffect=Shadow
FontEffectColor=#colorBG#
FontColor=#colorFG#
FontFace=#fontName#
FontSize=#fontSize#

[styleTextRight]
StringEffect=Shadow
FontEffectColor=#colorBG#
FontColor=#colorFG#
FontFace=#fontName#
FontSize=#fontSize#
StringAlign=Right

[styleBar]
BarColor=#colorFG#
BarOrientation=HORIZONTAL
SolidColor=#colorBG#
X=45
Y=1r
W=162
H=7